// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// voropp_Rcpp_interface
SEXP voropp_Rcpp_interface(StringVector argv);
RcppExport SEXP _voro_voropp_Rcpp_interface(SEXP argvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type argv(argvSEXP);
    rcpp_result_gen = Rcpp::wrap(voropp_Rcpp_interface(argv));
    return rcpp_result_gen;
END_RCPP
}
