# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' voro++ interface
#' @noRd
voropp_Rcpp_interface <- function(argv) {
    .Call('_voro_voropp_Rcpp_interface', PACKAGE = 'voro', argv)
}

